"""Actualizar created_at a DateTime

Revision ID: 07e1d59ea167
Revises: 83ddb48fcedf
Create Date: 2025-05-12 18:33:25.292975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e1d59ea167'
down_revision = '83ddb48fcedf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name_p', sa.String(length=100), nullable=False),
    sa.Column('last_name_m', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('member_number', sa.String(length=20), nullable=False),
    sa.Column('direccion_yvr', sa.String(length=100), nullable=False),
    sa.Column('privada', sa.String(length=100), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('id_front', sa.String(length=200), nullable=True),
    sa.Column('id_back', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('plates', sa.String(length=50), nullable=True),
    sa.Column('vin', sa.String(length=100), nullable=True),
    sa.Column('photo_rear', sa.String(length=200), nullable=True),
    sa.Column('photo_underside', sa.String(length=200), nullable=True),
    sa.Column('circulation_card', sa.String(length=200), nullable=True),
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('user')
    op.drop_table('resident')
    # ### end Alembic commands ###
