"""Corrige tipos de datos en Vehicle

Revision ID: 83ddb48fcedf
Revises: d835b5847f22
Create Date: 2025-05-05 15:27:58.433970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ddb48fcedf'
down_revision = 'd835b5847f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    op.drop_table('user')
    op.drop_table('resident')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resident',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name_p', sa.VARCHAR(length=100), nullable=False),
    sa.Column('last_name_m', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=False),
    sa.Column('member_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('direccion_yvr', sa.VARCHAR(length=100), nullable=False),
    sa.Column('privada', sa.VARCHAR(length=100), nullable=False),
    sa.Column('lote', sa.VARCHAR(length=100), nullable=False),
    sa.Column('id_front', sa.VARCHAR(length=200), nullable=True),
    sa.Column('id_back', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'viewer'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('make', sa.VARCHAR(length=100), nullable=True),
    sa.Column('model', sa.VARCHAR(length=100), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), nullable=True),
    sa.Column('plates', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vin', sa.VARCHAR(length=100), nullable=True),
    sa.Column('photo_rear', sa.VARCHAR(length=200), nullable=True),
    sa.Column('photo_underside', sa.VARCHAR(length=200), nullable=True),
    sa.Column('circulation_card', sa.VARCHAR(length=200), nullable=True),
    sa.Column('resident_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['resident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
