"""Agregar campo created_at

Revision ID: dc2d1239f6d9
Revises: 0c9d6e4fa3a6
Create Date: 2025-04-29 15:58:33.486864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2d1239f6d9'
down_revision = '0c9d6e4fa3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
